# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aadb0e2fda5d0d297863307ef644622bc3e3ed0e6a84659f94f58dccc196a99a1bed2e1aed6449eaaa5a1a9fa7afa7683cd8341af8dada90ba1444c9a288213e

test:
  secret_key_base: 9a5ad54995464903788cd973736955d0a43e4f08533b53e57bd078546f64845aea08b301f2340f803d4d29ce2c40b758f1815929e4ebcfe98520d07dcdffa907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
